name: Hello World Workflow
on:
  workflow_dispatch:
  # pull_request:

# on:
   # push:
    #    branches:
         #   - main
jobs:
    hello_world:
     runs-on: self-hosted
     steps:
        - name: Print Hello World
          run: echo "Hello, World!"
        - uses: actions/checkout@v4  